In [1]:
import pandas as pd

In [3]:
df_beat = pd.read_csv("PoliceBeatDec2012_20260707.csv")

In [4]:
df_beat.head()

,the_geom,DISTRICT,SECTOR,BEAT,BEAT_NUM
0,MULTIPOLYGON (((-87.7047252651434 41.975774430...,17,1,1,1713
1,MULTIPOLYGON (((-87.83365455041093 41.97535481...,31,0,0,3100
2,MULTIPOLYGON (((-87.90684167275818 41.97656175...,16,5,5,1651
3,MULTIPOLYGON (((-87.64491798475646 41.96972709...,19,1,1,1914
4,MULTIPOLYGON (((-87.63724132684592 41.96598776...,19,1,1,1915

In [7]:
df_beat[df_beat["BEAT_NUM"] == 1011]

,the_geom,DISTRICT,SECTOR,BEAT,BEAT_NUM
154,MULTIPOLYGON (((-87.71542078887018 41.86628981...,10,1,1,1011